[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc851d194757d6a4cc1196740c3485782b569c42"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "e14159163b527d1bdb925bd54346180ec89dadac68d7a74442a420e40124ad5c"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.aarch64-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd2720928632cffa93085b8eced6457a34bf6c34"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "6eb4d515ccf410d26a70be21f9d0151b56c1ef4f59416ed60fd0d68154a4eb28"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.aarch64-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d08a9d76c5832ef2f3c955010c3bf7457fd3bec"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "8e060b66997bc619f19b1847e7c959a15eb2e73abea908c7779e20d7f1f5c13f"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.aarch64-linux-musl-cxx03.tar.gz"
[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d31f3b522a4b35d8f9bdda8dc18b34dd10c104d2"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "b097818e645123c769e197a0e97efa8ba7a4397780df697a58618cc4900795d9"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.aarch64-linux-musl-cxx11.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d7262eceb1e72b26765320f9ba8424fcf9176e4"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "75587b4216606fe54f8ff59c719abbe505116246dc5758f0c67302747d93b76a"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "271b5bbb9b9850ec42dd05cbe04bb6bbb8d92409"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "c51d2a3acd20b6dfde3567826f936348a57fbd1d2b099c0e4ac1e2c8d2b3c46a"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "516ab6232529fb2fd6664341977a687c4c6f6305"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "2c4f8694208b652466c732cc6a6b3e9bd684395c55dc7110d51645d2a273e94c"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7dc4b9e42a6a6b8b67b85c39e0088bd66f13b34"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "a2eeb7634651aef215d4745fc99ea6054d08c4340c6d0387c290a56295a2c27e"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9df09afc66a04b346c060f5b621e8cffc3d28792"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "e70982315c7f95bec5f760654b558cd18d1a249cac4ec033241c85513d0fb013"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.i686-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "959e445bf233d644dfd782b29b42d68c95edc9a2"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "361f185b7d5ced9f8873bc19a02d46476b854f7cf100c97d8547cf1bec3be46c"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.i686-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb37987d86b834795269b8602f0927f6ca539d57"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "6bacfe5cb14587f95956df90052cd14b0525ef0b7ed4ea906ef8bdafeeb01d1a"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.i686-w64-mingw32-cxx03.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0808d4667a974233ec6dae5419be66bd56661946"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "10a64c29e18eb03330ba0895c8a980bf0da4707ee81d79a95a91f191724f4106"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.i686-w64-mingw32-cxx11.tar.gz"
[[openPMD_api]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e9b2c55f759fc9a92473aded6c7b42fafb867fe"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "d3fc1b68ed909ff419009751724ee026962e01f8202cd5f28ff9d1c5be7ea264"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3442af4db87406c1fcf8b3e0683f1891609e396"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "c4f717aabe36e0e3d348e55f03ffa6e7fc713e3c9c9d9b473e6922a0bf99167b"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "x86_64"
git-tree-sha1 = "e3fffe00fedf2088ae067c53625602e08c564ed8"
os = "macos"

    [[openPMD_api.download]]
    sha256 = "d5ac4fee47bd6f38f41a933c6317cfa4f76142b0b257b4c79394185df05c48d7"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.x86_64-apple-darwin.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eeaf31ab78d41be359c220bd69913f01b624a228"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "d128a222e2d118aa862e9a8fe6c1b230e25470a297e467e5e70565a7a26120b3"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.x86_64-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa85356cd249647806879ac192708149e689776b"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "0c2737158104a2df79efdd3b4b1c440256088e84cb0fccd26e4a5cea0204cd6e"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.x86_64-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5399076a4051339c6ab52a16fbabb1dc524835bd"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "5fc5b1dcc2c9804a90bea3611614982747708041cda1e9b2dbc97835bb62005a"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.x86_64-linux-musl-cxx03.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d3c82284da8cf8fed7b07211d5438454c246973"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "ec5b71fff2c28b60a85ee63dbb275661bdf5e200b48046d552216ae177c8f738"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.x86_64-linux-musl-cxx11.tar.gz"
[[openPMD_api]]
arch = "x86_64"
git-tree-sha1 = "d57240a709712ee9f1d155fe4d58c5e8134de839"
os = "freebsd"

    [[openPMD_api.download]]
    sha256 = "bcd6d0a50daac3632865a264a5dd97c8017d8bc2bef1c2cde231cde4b7bb39d8"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.x86_64-unknown-freebsd.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41c8d21fd4df1b565b8604a68d5fdc702ac5a2c1"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "df348c5a501c571347d16abca078c8228c539963137ff3d7482dfb62a2ac5f2c"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "897e5e71205423a06e83db0af02bed61e406ef8f"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "12db2a25b15eceb78b716294732354f4e3a6451416411d2faa7ea23a3396172f"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+2/openPMD_api.v0.14.0.x86_64-w64-mingw32-cxx11.tar.gz"
