[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "155f3a370a9235b5a78b67601746e953e56d0dd1"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "6b2fedbb339e6cbe6d567ece78c7a61fe479c2138626219316016a6cfa1d1a85"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.aarch64-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7117b5e59fe4227e5068a87fbe8c3658cfc0f499"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "bcfc47321d622434c82f85b1ed17a8acea2e0056a3e23cff5414d6e7ecd90a98"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.aarch64-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31d8308c400b8552adb21a7ef3514a15eb922256"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "49d24e214d061e493624b83bbec8c31ffd0d421714fff3327704540098f598eb"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.aarch64-linux-musl-cxx03.tar.gz"
[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1527378d76953c3bb50d80fd33b3a96e023d7da6"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "363bdae6cb517db8b19953b8766f5ba1e7fe0dcf5c1d6954f68ea9cb5dd748e3"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.aarch64-linux-musl-cxx11.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "54b2050e3c0d846365f9bbf7e81fec1aa9d17c96"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "eae95a27d20010599528959aef31d5e779227716c93e19187bffd490e9f33ca2"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42504c64b6d15970ab4c9dadedb768b9730d3bb9"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "82c454d817883f7acbbbc2db9ed01d8d2cbe188d9e5376f8896e050c5e431f07"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbea94fce641b0d496500f7e4f5dbc0e5a45f148"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "52066ee2d190ea47d33dba536a1e621e94744f641a3bc56cefea5c0d912facce"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "281dd7f99df0b1afbc006ca01b43d885053842d1"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "ed1d46256d8bb61bad9935fb7eda56b9b87fc911a6676f1a0cd63679a8f7fd3e"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dac18b5c36819c4d98abe21983727730d853600c"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "baf3f86ea12806226a71255ea887a2c507412d49b18df1afa2abcf0de4f56f97"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.i686-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63246aa9e32f6b196c2d7fa0e61c9d9872d48fa4"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "4e55b830b9d6b685148d32581f1001f18a8fd98b3b46d3ebb091b81113e5f5d0"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.i686-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3694976543ea745fb7315939fbb463a260512c8"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "43e269a32d75eaf9cc0652deec321552d327b05da14e46e4ff64b36ae790fcd1"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.i686-w64-mingw32-cxx03.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "823aaf7e308c588562e941f8d0b053f1f37597e8"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "f97a524b6e2a8df41a054419ccff469fe2296b29a171dd5df736842579bea9bb"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.i686-w64-mingw32-cxx11.tar.gz"
[[openPMD_api]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61bb9f3e063e7b3a24a03668fe6e8407eff28848"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "92ed521dd0c693105d6ee17b7751f31797b803000047ad043b3336d7169242fe"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d88c4e5c8b20d50610dccdfb1122a9496b8be3af"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "27b0aa73d23463a009f21af47e1f119ae8954951acc14d511df55092572018c8"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "x86_64"
git-tree-sha1 = "051d3acbc69fb5e7a565639efd6aa66b4555c05f"
os = "macos"

    [[openPMD_api.download]]
    sha256 = "f073e34dbca93579c21393e3e27a62151c99893cd79fc0b44acc429dd2cccd7e"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.x86_64-apple-darwin.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "600ebf41fedb2be2701e30bc0e8c350342f7a3db"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "cf65e3678d9ecf54b7afe381a201dd3c4e3925e971c283302e5e0e650f7ff26f"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.x86_64-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54f4cf9f5808f11aeaeb78c0cbcb50124ede4af1"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "61e8cbca46a14a272eac42bf19458bd3c006e8475d97014fdb1903fcbab29241"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.x86_64-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "274686a353c27a36024d761ca473583e48eccf52"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "8c8f51eced0911be2581c0e305ef55e2d0401d2626da53e19c0496c0fb46acc3"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.x86_64-linux-musl-cxx03.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "807aca3176fecf7b4830608ca8428c712803dbef"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "a441497b4cf058ca682a9fb4bd8abde094f6692fb33c6479a43610495ebc8445"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.x86_64-linux-musl-cxx11.tar.gz"
[[openPMD_api]]
arch = "x86_64"
git-tree-sha1 = "b7cfdfbe9347be8b9ac3c96aaa15d31f9b57f07d"
os = "freebsd"

    [[openPMD_api.download]]
    sha256 = "7be9a19014c886ba0b8384d1f95bb53789813efdb01af6a73f8e3ec916dfb79b"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.x86_64-unknown-freebsd.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dcfb965e2bc3992d2ef26ab6c921ca2ed17189c7"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "1b2f1565867e788f7220f78619981eaff07153ae3261dad41f563eb3e07a1c1c"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd411ba124a79f54a0825b056ff8d1dfe15cb690"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "89719a38ebe391ec4d0219666e15928fdcdb4316f39a0bb1644a86161e45b7c0"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+1/openPMD_api.v0.14.0.x86_64-w64-mingw32-cxx11.tar.gz"
