[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f29e670e2df9cf61df058f382b3abc14a3deb59"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "a3517017c63bd57ecfa5de27d4105b7f04adc8f205ae0c5ecfcb103c3e3be1fd"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.aarch64-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b102f5caf608e85c3c233c4c8bcc1edf7bded8ae"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "c0ad2c0f2ceb4a5b803d318b8bc10e0f7ed63f0a50f41b1a5fc80ed23a3eb63d"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.aarch64-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "185dc47cbd901a3a5daa6cf68c62c8e294595eed"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "f888e9db37427372aad85c8a6f89180328059f3ae5eeef26a3f29dfe212c3538"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.aarch64-linux-musl-cxx03.tar.gz"
[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ba0e80006454953db0b99b6c7c4974eec5b725f"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "a1ac01a66c5d5c957d14c409a90d3e1a7c19ffac64c3257490c936d5ef5a630a"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.aarch64-linux-musl-cxx11.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1800606fb6366110ea9a13d630a887d3f40e78e7"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "638893ccabf292d9a86f0efdf89c17bb778574e5c782120fbf7ee91204dc3862"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62275a1cb98adeab0f7cb5b37365805ddbc5c77e"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "60cab6944eab396cd129a5586052da73f1da02fbc03e2c0f2f71142cfc17e5e4"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c72a4f2771bc763e6e5f914236977d15c7ebc2aa"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "b0490ea41739051312e954dab0d776d1a7cbab23823df4e3d7250091964134d5"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34456ded3613ac447a741b08a6a04827294f24f8"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "65fe727fd784d76f4f47bb77610a352caec8b5d08767743c31269c97193bb3ef"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b94fa690349f6f8f58c0d7efeb6c3bfc45db483"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "b6b5ac364a8babb8dea39e53ccf4aad950ce3767ccd86c1b6c589c304f4adf47"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.i686-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb636680645d121f719c9aca00287f769db40b28"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "368cdde4f50a8f57e30045ef0c810cb1b6fb3e02ad29bfa7bcc4fd95d0cb509d"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.i686-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "537e5a53aa0054cbc5615bba3b3fb255ba265145"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "7e4d616526f88c9171f3a8beefe271c4d270bb40cd7e0b5eaab00924eff58931"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.i686-w64-mingw32-cxx03.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0910fb208004b691fc03804e80a3f6b15d3cb67b"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "2cb83afc94a5f902cbcc24957a9068e0f0f7679a9521fb2852615f58b18a5b30"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.i686-w64-mingw32-cxx11.tar.gz"
[[openPMD_api]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9566b6f5533d56495620a80fb1458173048e13d"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "515fbb4dc64bdc3b47e8da73c97d7cc7c7ec8f1dd13641a3cea8846d69b43e0a"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "033ade232ad6ac5c59577a78f2a00e12619e560f"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "0943409a290f4a37e89db65ac63ad3e75bcd4ff5f6e1f741f7fd4a18f6477113"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "x86_64"
git-tree-sha1 = "c6bb6d6e446fde44fe1a33d0a014c5e71a282d30"
os = "macos"

    [[openPMD_api.download]]
    sha256 = "e72e2ebe43750983af7a084053c9d56ea3a7a75d079462789cac02357441a813"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.x86_64-apple-darwin.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be0468ac489dca118d5bf39b198480a54f24b00f"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "02a04eabb9847f111e66bc61b38aa18bf38ace000608cda382385bb2edb58f28"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.x86_64-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e77f6ac5cb8005a29b533af71aa283ddebc27e4f"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "f2d671db89b309753eed377deec8abbc4d04eedfd8990f65d5ab4e782b4322cf"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.x86_64-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d01b27e5723d60b8e241358544c8325c6742f8bb"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "30deaef97d57df94090fabdc1bf50b105da3eb7f411a65644ec97a0f00329a0f"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.x86_64-linux-musl-cxx03.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5bb2ce05e532b18fb83405b0a222c48868e9d61"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "1d437228e9d371db6c02e1743e1a4cf347882e5bae6a5aba3b5ab9278dca2757"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.x86_64-linux-musl-cxx11.tar.gz"
[[openPMD_api]]
arch = "x86_64"
git-tree-sha1 = "fb286ef783f52f7c132d69e04d4170d6444eff8d"
os = "freebsd"

    [[openPMD_api.download]]
    sha256 = "62b38062b0aaa47ffcc27d96d83748544eefd2fa2ad9e1e5b73d014a772b4f00"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.x86_64-unknown-freebsd.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0dc689d28030e73431ede001ab7bb3e0f38b579d"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "9a3b6e0644018a4a16756b77298c6be12d02b8ba1d30f4286aef159d06d2c0fe"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a39ac7c4d7b6575c95e065d1a34ffeec07e8075e"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "478410afb167f99d87319676d8cd165d2dd99d36c795e697eecb10db0ea64552"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.0+0/openPMD_api.v0.14.0.x86_64-w64-mingw32-cxx11.tar.gz"
