[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49d9c26938291ab2d91b85f7d5b1e0d6981b0b6b"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "86dd5668c6aee33f16eba007fa3997749c5dc39b7672cbd0d709b3c14d09526f"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.aarch64-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e54f2ef625183351af4c9b0c798d4d5eb9ffc2c7"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "7d722612e8d1dc12443b72b7570ff86a7df4b77187d56a0a1759ccf55d29c2a5"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.aarch64-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3e7db59420cf4379892e20f1e891720439a77c8"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "a9534f2516dcc3c2a976293587af950a3d4955b540cc9ee64d957b0c683f6054"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.aarch64-linux-musl-cxx03.tar.gz"
[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b41349a38ee320016f2f35e00576ae3509992605"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "e8a383dddba1c6b27d44e4b1a9f0a0f04f63ee3567f22b657c0408745acbea80"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.aarch64-linux-musl-cxx11.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97b0f3d66fd70fc25b205bdbdea499812b29e8f5"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "af538edcbd29a7ef5ea9b56fd5953d86309791af082a2088dffdcd76c02b338e"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3708d8c6d003cf2aab166109a724f8e28015244b"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "08a94b54af5b1c077fc9a09f44d7b69199bf0c6f6fb4ea6d2d1150ff3dacf0ba"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c28e739ce8f8742c8e87728fd6f2f34e3c9eeb4d"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "64a6140ccded876e036891ce886ad08ab369549af18c3572da31e37808f6718e"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc5336890c1e89f8cc924f3bbeea3ce3628dfb54"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "a30e453af141fe0d250c8316aca5f1890f9e72e6cf39338608058667b4f87d7d"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "800295c9cb35dcadf259022a309df32ca35e8123"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "61f478b678178ee26f54cee18249f8ffab71799acba2309e0a857600d4e211dd"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.i686-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3041d07d761a791d414b24ab1b1aea76601d73aa"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "7081f2d7cf11bb27d3b299a57e2bff6941709148243bbac5863443302a376eae"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.i686-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e23e5e772e8729bb8ec6a9d281c86d30508dae65"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "1134559ca9252918671cdf2797c06e1f5beac694baab7b66cdf616bf1ef4d458"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.i686-w64-mingw32-cxx03.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "610ae8a95c402484ed812197f427e0c19987c68c"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "6b05c4fb7e48c40b238e429639a1e2478b226774fbe05c2bc302606f1b3567d8"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.i686-w64-mingw32-cxx11.tar.gz"
[[openPMD_api]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ee2da2909248af877fb4ca1a6cfb5ddfbb09b0e"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "1691b2c97e622cabe034156bd093f0dc0d8bc29027bf70ec82c18162f82454c3"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ca877d332305b3baed62097729557ecd0e138f4"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "2cdb2df4246328cbc2ff791bccdc56528f4c874fe3482ce6d9fe646a43edc5c0"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "x86_64"
git-tree-sha1 = "5805d2eff5f20e3567401bb420ae93a2dcc07ca2"
os = "macos"

    [[openPMD_api.download]]
    sha256 = "7fe9e4807cfbe4a1d560c34aa33c3b421a0083bca7854efb51d9c9a58396c62b"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.x86_64-apple-darwin.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22cc8fddb509c8ad07df17609ad8a78049dab3b4"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "d92137c80dbf2fa8597e87935b5dde62a88d16b78f3a50bf162df0ccf0a4b84b"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.x86_64-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "580529f108380718e9cc260e0ce7aed93701c94b"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "e3b6f4684c97d95423faec0e919d8d2d3b252f68c8cf815063d3f5a8ddb288c6"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.x86_64-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a7ade9acb682e59332de536a33a6741109e5413"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "c5fb807470257890e847fa0263b2687e1b9c0bfc9a3bdcd9deb124f739842848"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.x86_64-linux-musl-cxx03.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "787e3cafba88c4f612a1a888c55b82a530794e8b"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "467aeb11504da7afeaffa62aa6067cc53e142e7d6463cc04d8eba3318d2853da"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.x86_64-linux-musl-cxx11.tar.gz"
[[openPMD_api]]
arch = "x86_64"
git-tree-sha1 = "834af1505ab95e7cb5db3cc4d0b4a9e9f39af144"
os = "freebsd"

    [[openPMD_api.download]]
    sha256 = "f05a9d7ddacbd24d2fcb8d70f9aa0b0f752c531bbe636e6b4a0ea1502347e3b7"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.x86_64-unknown-freebsd.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fc573c2abb15448167f1c7ef61b3eeaffd5d486"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "4aad34082b4fc506c790b8069ee5e09438bd923dea346071086f31ce51747de1"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e13337cd6eba7d88a90b024cff1ac8877d03204"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "ba1ec2ac9aa853b87d678ba984756fdf8c43630d46dfa07699add40e6fa857c7"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.2+0/openPMD_api.v0.14.2.x86_64-w64-mingw32-cxx11.tar.gz"
