[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "445ccf19ed26970786a693660f4a5180c3f4e263"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "789be95c3edc6aa9ce329e731bb5bfd4b06c3a3c040920525498a9b0cb66f015"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.aarch64-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b933b60ad14cb2353ab9c890b864dfbf92e3644d"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "ee0955591da7dd97a392143484582c9e084dd619f6db348baeaf11dba024d9e9"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.aarch64-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d75fcca80acad25357718669a362c4ca2b309a7"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "fa65e7e8ca114eacd0136fb8316f59f9f7a5636675b30a914ca33ff96079aec3"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.aarch64-linux-musl-cxx03.tar.gz"
[[openPMD_api]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99e522c4d60d5a199f5873ce5f22850beb23e7f4"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "b5c4d8edaffa6686b0c375d224805f2c9a24d3a14e3f43c9156ee804783c509f"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.aarch64-linux-musl-cxx11.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adc81bd0baa94eeb17bd7a826acb3fdc0ed53339"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "a3898a8f330e7ecc5c6d526f933954a8b271bb953faa8a4f79554861472cdc10"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09453349d760753be49c40092a13dc65e36ad14c"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "563c9801714f8c5dfadf47684c1fe8fa6baf72594c6565566e7f3dfff4aead11"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c63e1a910469df44a4e3de48ca5e111ef59ef23b"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "9fdd7e19865ceb838ffd73df2892c43f156c12f07a2fa33afb8d9d7615f193bb"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[openPMD_api]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75b5c712f3f68b31ec7a983e9f16b6cebd86b49b"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "4bc7a12ae79ef44768afd93a0553aaf5c4866a6d2951ccd760607c034999b2b4"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02ce8b91deb005355a0c98f8a10554379da857d4"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "696d4677d677ac71bb08c843d0986c50e2b7c9e18bf3c99fb155ca5fab7efed9"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.i686-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1cc148804be01ec28aca558ce40fcd021eb5f047"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "19042d0b3ce8ad7b5f0dd2ce790c247fc7bcfb4ec9333c712e7b119704430767"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.i686-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b85f25f1e01215ea6be4c8d8e447bbda7788f4b7"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "9d894f18413df7f048615185cf80b5c82ace89e0eb29c6d92076574adeb41897"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.i686-w64-mingw32-cxx03.tar.gz"
[[openPMD_api]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd979c18283949c72c82ae2cf3b9c9f506f880ab"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "975b12291ccdfbe2cd050859ba3bf9734af86860ebd47a0b07bf4637a76a328c"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.i686-w64-mingw32-cxx11.tar.gz"
[[openPMD_api]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa790d7f22e3c80b1d0895e14c4163d90641a1f5"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "d6b3971ba3223c865127a8f72af694b6aceffb7b2dcc9678e96feb200b8e2acd"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a091e6f026cc914734d496cce679c72456809767"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "ea55945fa4e41efd7a9146bcd0a42a664a61c74f3e90beed49b819746490b079"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "x86_64"
git-tree-sha1 = "21edd50db07efea080c483b2d9c1e45bd1184527"
os = "macos"

    [[openPMD_api.download]]
    sha256 = "a67c38827c10454a7cc9eb04ebad726965f8bad250aec6c497cb466645bf699d"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.x86_64-apple-darwin.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b113d2f3fab671af017f21ff20c42d801571687d"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "2b03a9371b86be52904817b6cfe7c2a234443a5714ac9deeeada0035c783ff29"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.x86_64-linux-gnu-cxx03.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95487857874be4b4d4b0ca1d1b0c2fe3b20ee171"
libc = "glibc"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "e931ed3cd20fc86ba67cb5f65ea9b4001d0f8ea6776615709f587c26c8831960"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.x86_64-linux-gnu-cxx11.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18b9c18dc4273c7a2cd9a1a5a1d59eef98384e04"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "1e662cc08ee2bf20efc67bb2793793867c3e8ef1552b3542bcbf3d7889831a97"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.x86_64-linux-musl-cxx03.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "243f48c02b25fd1c6b88e0de71e30d74a025901c"
libc = "musl"
os = "linux"

    [[openPMD_api.download]]
    sha256 = "1d399e537a03a5188249c1c952a2a80211e0962be1033b11af6111a7aaeeee04"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.x86_64-linux-musl-cxx11.tar.gz"
[[openPMD_api]]
arch = "x86_64"
git-tree-sha1 = "3890242a459cd12b1a801786eec9dcfb06fc6b6f"
os = "freebsd"

    [[openPMD_api.download]]
    sha256 = "38de5399b92ca458bff6fc111ad6e8dc6017cdb1ee0c374e9215be7a0a168b83"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.x86_64-unknown-freebsd.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a8e1b83ab828999a4a15df20f5353fb7510034f"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "edbb8739d17a7b6c8300a0358e8f683357c6c0d951721c5eb3e1a2b31cfdbd15"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[openPMD_api]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6fed46a2b60db5829492d9abf39ce578021f73f7"
os = "windows"

    [[openPMD_api.download]]
    sha256 = "a410cd07824875024fb5c19b9459199215578f717c3f7bdfd7a5c55e5c83d0f3"
    url = "https://github.com/JuliaBinaryWrappers/openPMD_api_jll.jl/releases/download/openPMD_api-v0.14.1+0/openPMD_api.v0.14.1.x86_64-w64-mingw32-cxx11.tar.gz"
